### ISSUE TITLE
Font screwed with simplebrowser

### ISSUE THREAD

**Issue by TeLLie** [bitwiseworks/qtwebengine-chromium-os2#33]
Hi
When use simplebrowser and i go to f.e github or google or os2world 

 the font is screwed i think.
As i see only picture.
Some sites are showed well, like youtube
I use f cache but that don't help

**Comment by dmik** [comment]
We had an issue in Mozilla with missing font glyphs, see https://github.com/bitwiseworks/mozilla-os2/issues/23. It may be related to downloadable fonts (and  @font-face) in chromium as well. Worth checking.

**Comment by dmik** [comment]
@TeLLie is this still relevant? I heard you fixed that by installing proper fonts. Please share details.

**Comment by SilvanScherrer** [comment]
@TeLLie any news on hat?

**Comment by TeLLie** [comment]
Hi

If i change font on this laptop the issue is gone
I don't see this behavior on my second laptop.
But i have a test desktop and there i also need to change font.
But i need to change font in the settings from the browser...

Op do 25 nov. 2021 12:40 schreef Silvan Scherrer ***@***.***>:

**Comment by dmik** [comment]
This in fact has nothing to do with Qt or Chromium, it's a fontconfig/Type1 font issue, see https://github.com/bitwiseworks/fontconfig-os2/issues/1. Closing this one.
