### ISSUE TITLE
Failure to open local html page

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/qtwebengine-chromium-os2#50]
This is a counterpart of bitwiseworks/qtwebengine-os2#7 but for Chromium. See the original ticket for more info.

It turned out that the problem is hidden much deeper and in Chromium, not its Qt layer, hence a new ticket.

**Comment by dmik** [comment]
JFYI, the web engine test drop is available at http://rpm.netlabs.org/test/qw.7z. Here it fixes both Dooble, Otter and simplebrowser.

**Comment by lerdmann** [comment]
I can confirm that the temporary qw.7z fixes the problem.
